# -*- mode: ruby -*-
# vi: set ft=ruby :
$script = <<SCRIPT
echo Installing dependencies...
yum -y update
yum -y install unzip wget
sudo yum install -y epel-release
sudo yum install -y unzip
sudo yum install -y curl
sudo yum install -y python-pip
sudo yum install -y java-1.8.0-openjdk-devel
pip install --upgrade pip

echo "Installing Docker ..."
yum check-update
curl -fsSL https://get.docker.com/ | sh
sudo systemctl enable docker.service
pip install docker-compose --force --upgrade
SCRIPT
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos/7"
  config.vm.provision "shell", inline: $script

  config.vm.define "s1", autostart: true, primary:true do |s1|
      s1.vm.hostname = "s1"
      s1.vm.network "private_network", type: "dhcp"
      s1.vm.network :forwarded_port, guest: 80, host: 8080
      s1.vm.network :forwarded_port, guest: 81, host: 8081
      s1.vm.network :forwarded_port, guest: 82, host: 8082
      s1.vm.network :forwarded_port, guest: 83, host: 8083
      s1.vm.network :forwarded_port, guest: 84, host: 8084
      s1.vm.network :forwarded_port, guest: 85, host: 8085
      s1.vm.synced_folder "../", "/dev/workspace"
      s1.vm.synced_folder ".", "/vagrant", disabled: true
      s1.vm.provider "virtualbox" do |vb|
         vb.gui = false
         vb.memory = "5120"
         vb.name= "Spring Boot Zull POC"
         vb.cpus = 4
      end

  end

end
